export const LOAD_POKEMON = "LOAD_POKEMON";
export const LOAD_POKEMON_FORMES = "LOAD_POKEMON_FORMES";
export const LOAD_POKEMON_EGGS = "LOAD_POKEMON_EGGS";
export const LOAD_POKEMON_EVOLUTIONS = "LOAD_POKEMON_EVOLUTIONS";
export const LOAD_PREVIOUS_POKEMON_ID = "LOAD_PREVIOUS_POKEMON_ID";
export const LOAD_ALL_POKEMON = "LOAD_ALL_POKEMON";
export const POKEMON_NOT_FOUND = "POKEMON_NOT_FOUND";
export const CLEAR_POKEMON = "CLEAR_POKEMON";
