export const LOAD_POKEMON = "LOAD_POKEMON";
export const LOAD_ALL_POKEMON = "LOAD_ALL_POKEMON";
export const POKEMON_NOT_FOUND = "POKEMON_NOT_FOUND";
export const CLEAR_POKEMON = "CLEAR_POKEMON";
export const UPDATE_POKEMON = "UPDATE_POKEMON";
export const UPDATE_POKEMON_FAILED = "UPDATE_POKEMON_FAILED";
